
renderwelcomescreen ()
ldb = {}
//ldb.mycnt = Country[5].split(' ')
//ldb.mycnt = 'hehe'
rendermenu ()
renderinfobox ()
rendermenubuttons ()
renderstatebox ()
rendermapframe ()
rendermap ()
populatemap ()
//rendercapitals ()
//renderonlycapitalmode ()
//randommode ()
//opacityhandler ()
//distributepower ()
renderdiplomacy ()
renderpreference ()
Allymap[0] = []
//renderpowerranking ()
//renderhandbox ()
//populatehandbox ()
document.getElementById('newgame').click()
generatefriendmap ()
inithistory ()
renderwhokilled ()
//populatehistory ()
//startgame ()

//rendercountrystats ()
//mapgenerator ()
//ldb = JSON.parse(localStorage.debug)
//renderhistorygraph ('ccit')